# Generated by Django 3.2.5 on 2022-03-04 12:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clubs',
            field=models.ManyToManyField(blank=True, null=True, related_name='clubs', to='app.Club'),
        ),
        migrations.AlterField(
            model_name='club',
            name='admins',
            field=models.ManyToManyField(blank=True, null=True, related_name='admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='club',
            name='applicants',
            field=models.ManyToManyField(blank=True, null=True, related_name='applicants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='club',
            name='banned_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='banned_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='club',
            name='books',
            field=models.ManyToManyField(blank=True, null=True, related_name='books', to='app.Book'),
        ),
        migrations.AlterField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
