# Generated by Django 3.2.5 on 2022-02-10 03:13

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubevent',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='end_time',
            field=models.DateTimeField(validators=[app.models.FutureDateValidator]),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='link',
            field=models.CharField(blank=True, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='location',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.DateTimeField(validators=[app.models.FutureDateValidator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(null=True, validators=[app.models.PastDateValidator]),
        ),
    ]
