# Generated by Django 3.2.5 on 2022-02-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220210_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubevent',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
