# Generated by Django 3.2.5 on 2022-03-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='group_chat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
