# Generated by Django 3.2.5 on 2022-02-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220216_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='liked_books',
            field=models.ManyToManyField(blank=True, related_name='liked_books', to='app.Book'),
        ),
        migrations.AlterField(
            model_name='user',
            name='read_books',
            field=models.ManyToManyField(blank=True, related_name='read_books', to='app.Book'),
        ),
    ]
