# Generated by Django 3.2.5 on 2022-02-03 03:49

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(validators=[app.models.DateValidator]),
        ),
    ]
