# Generated by Django 3.2.5 on 2022-02-07 23:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_club_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='eventvote',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='club_event',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='club_event',
        ),
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.DeleteModel(
            name='BookRatings',
        ),
    ]
