# Generated by Django 3.2.5 on 2022-02-07 21:11

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_club_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(null=True, validators=[app.models.DateValidator]),
        ),
    ]
